spring.application.name=dev-web-ide
# DB Setting
spring.datasource.url=jdbc:mysql://localhost:3306/dev-web-ide
spring.datasource.username=root
spring.datasource.password=1234

# [JPA Setting]
# DB ??? ?? ??/??
spring.jpa.hibernate.ddl-auto=update
# ??? ?? SQL ??
spring.jpa.show-sql=true
# SQL? ?? ?? ??
spring.jpa.properties.hibernate.format_sql=true
app.project.storage-root=./storage